version: "3.9"

services:
    flask_db:
        container_name: moneyminder
        image: postgres:13.2
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=moneyminder
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: {}
